# Generated by Django 3.1.3 on 2020-12-01 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201201_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='student_group',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 16, 4, 43, 317845)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 16, 4, 43, 316847)),
        ),
        migrations.DeleteModel(
            name='Special_Students',
        ),
    ]
