# Generated by Django 3.1.3 on 2020-12-02 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201201_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 3, 45, 617928)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 3, 45, 617928)),
        ),
    ]
