# Generated by Django 3.1.3 on 2021-01-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20201204_2047'),
        ('questions', '0016_auto_20201218_0843'),
    ]

    operations = [
    ]
